query Reviews($filter: ReviewFilterInput) {
  reviews(filter: $filter) {
    id
    shopName
    workerName
    estimatedAge
    bodyType
    bustSize
    heightCm
    personality
    headline
    detail
    serviceHighlights
    rating
    reviewRating
    damage
    createdAt
    updatedAt
    author {
      id
      name
      email
    }
  }
}

query Review($id: ID!) {
  review(id: $id) {
    id
    shopName
    workerName
    estimatedAge
    bodyType
    bustSize
    heightCm
    personality
    headline
    detail
    serviceHighlights
    rating
    reviewRating
    damage
    createdAt
    updatedAt
    author {
      id
      name
      email
    }
  }
}

mutation CreateReview($input: ReviewInput!) {
  createReview(input: $input) {
    id
    shopName
    workerName
    estimatedAge
    bodyType
    bustSize
    heightCm
    personality
    headline
    detail
    serviceHighlights
    rating
    reviewRating
    damage
    createdAt
    updatedAt
    author {
      id
      name
      email
    }
  }
}

mutation DeleteReview($id: ID!) {
  deleteReview(id: $id)
}
